### ISSUE TITLE
Static IP configuration example

### ISSUE THREAD

**Issue by dsjstc** [tinkerspy/Automaton-Esp8266#1]
As compared to DHCP, a static IP config on this chip apparently uses about 1/50th the time (and hence power consumption) to establish a connection.  I struggled briefly to make this module connect with a static IP configuration, but I'm too new to Automaton **and** to the ESP8266.

If it's possible, would you mind posting an example of connecting with a non-DHCP configuration?

**Comment by tinkerspy** [comment]
Hi,

That sounds like a good idea, but I don't really have the time to look at it at the moment.

Rgdz, Tinkerspy

**Comment by dsjstc** [comment]
OK, if I can figure out how to make it work, I'll send you an example 
and/or a patch.

**Comment by yowelf** [comment]
Hi, 

@dsjstc to set an static IP  you need to initialize all ip values of the connection and after begin the wifi. Those parameters are valid to connect with my phone as hotspot. The not esp8266 arduino core libraries allows setting only the ip adress, the ip and the gw etc..

```
#include <Automaton.h>
#include <Atm_esp8266.h>

// Minimal Hello World webserver with led control

Atm_esp8266_httpd_simple server( 80 );
Atm_led led;

void setup() {

  led.begin( D5 );

  IPAddress ip(172,20,10,10);
  IPAddress gw(172,20,10,1);
  IPAddress mask (255,255,255,240);
  IPAddress dns1 (8,8,8,8);
  IPAddress dns2 (8,8,4,4);
  
  WiFi.config(ip,gw,mask,dns1,dns2);

  wifi.begin( "MySSID", "MyPASSWORD" )
    .onChange( true, server, server.EVT_START )
    .start();

  server.begin()
    .onRequest( "/on", led, led.EVT_ON );
}

void loop() {
  automaton.run();
}
```

**Comment by tinkerspy** [comment]
Awesome, thanks yowelf!

**Comment by dsjstc** [comment]
Outstanding!  Somehow I didn't get the notification until now, but it's much appreciated.

Or it will be, when my electronics bench is reassembled.  :-(
