### ISSUE TITLE
I cant find the library dependency

### ISSUE THREAD

**Issue by yowelf** [tinkerspy/Automaton-Esp8266#2]
Hi tinkerspy,

I am trying your framework and when I am getting an compilation error. I include the Atm_esp8266.h, but this call to other that it missing. line 4. there are many libraries about ESP8266. what is it this?

```
#pragma once

#include <Automaton.h>
#include <ESP8266WiFi.h>
#include <WiFiClient.h>
#include <ESP8266WebServer.h>
#include <WiFiUdp.h>
#include <Hash.h>

#include <Atm_esp8266_httpd_simple.hpp>
#include <Atm_esp8266_httpc_simple.hpp>
#include <Atm_esp8266_wifi.hpp>

extern Atm_esp8266_wifi wifi;
```

I am newbie. Sorry if I mistake writting here

**Comment by tinkerspy** [comment]
Hi yowelf,

I haven't looked at the esp stuff for a while, but I think you need this one: https://github.com/esp8266/Arduino

Rgdz, Tinkerspy

**Comment by yowelf** [comment]
Oh thank you so much. I think my arduino IDE doesnt find the library in the library manager because is outdated IDE. after that I was having other dependencies problems almost..

if you want close and delete the post to clean your issues list

Regards,

**Comment by yowelf** [comment]
thanks for your help, but I have been studying the problem i have

The library you link me is to develop over the esp8266 directly. So to run i need to select esp8266 generic as the board connected to the arduino IDE. without pins

I understand that the code you share in your traficlight is to run over: arduino IDE —>	 arduino/genuino uno —> esp8266 board.
so the selected board in my ide should be Arduino/Genuino UNO board

After set the queue.h header in src folder of the ESP8266WiFi library, now the issue is 

In file included from /Users/aitor/Documents/Arduino/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h:28:0,
                 from /Users/aitor/Documents/Arduino/libraries/ESP8266WiFi/src/ESP8266WiFi.h:34,
                 from /Users/aitor/Documents/Arduino/libraries/Automaton-Esp8266/src/Atm_esp8266.h:4,
                 from /Users/aitor/Documents/Arduino/semaforo_v0.01/semaforo_v0.01.ino:6:
/Users/aitor/Documents/Arduino/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h:27:22: fatal error: functional: No such file or directory
 #include <functional>

is like I need to set the board as ESP8266 to change some path to include this parameter (and <memory>) but I need to set the board as Arduino/Genuino UNO board to upload, compile and run the programm

I need to resolve that because after many months searching I am going to develop my final proyect. At least a part.

Thanks,
